package mnj.ont.model.services.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 04 17:20:49 BDT 2016
// ---------------------------------------------------------------------
public interface MainAM extends ApplicationModule {
    void populateLines1(String OrgId);

    void populateLines(Row poprow);

    String getPopulateValue(Row r, String columnName);

    String getOrgId();

    Row createBPOLines();

    void callFetch();

    void popupSelectActionListener();

    void popupDeselectActionListener();

    void fetchLines();

    void saveActionButton();

    void testDate();

    void headerExecute();

    void copyDocument();

    void amendmentAction();

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);
}
