package mnj.ont.model.popup.views;

import java.sql.ResultSet;

import mnj.ont.model.popup.views.common.FillLinesVO;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 03 17:20:06 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FillLinesVOImpl extends ViewObjectImpl implements FillLinesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public FillLinesVOImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }


    /**
     * Returns the variable value for startDate.
     * @return variable value for startDate
     */
    public Date getstartDate() {
        return (Date)ensureVariableManager().getVariableValue("startDate");
    }

    /**
     * Sets <code>value</code> for variable startDate.
     * @param value value to bind as startDate
     */
    public void setstartDate(Date value) {
        ensureVariableManager().setVariableValue("startDate", value);
    }

    /**
     * Returns the variable value for endDate.
     * @return variable value for endDate
     */
    public Date getendDate() {
        return (Date)ensureVariableManager().getVariableValue("endDate");
    }

    /**
     * Sets <code>value</code> for variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(Date value) {
        ensureVariableManager().setVariableValue("endDate", value);
    }
}
