package mnj.ont.model.lov.views;

import java.sql.ResultSet;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 18:09:02 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContractVOImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }


    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }

    /**
     * Returns the variable value for p_buyer_name.
     * @return variable value for p_buyer_name
     */
    public String getp_buyer_name() {
        return (String)ensureVariableManager().getVariableValue("p_buyer_name");
    }

    /**
     * Sets <code>value</code> for variable p_buyer_name.
     * @param value value to bind as p_buyer_name
     */
    public void setp_buyer_name(String value) {
        ensureVariableManager().setVariableValue("p_buyer_name", value);
    }

    /**
     * Returns the bind variable value for p_season.
     * @return bind variable value for p_season
     */
    public String getp_season() {
        return (String)getNamedWhereClauseParam("p_season");
    }

    /**
     * Sets <code>value</code> for bind variable p_season.
     * @param value value to bind as p_season
     */
    public void setp_season(String value) {
        setNamedWhereClauseParam("p_season", value);
    }
}
