package mnj.ont.model.lov.views;

import java.sql.ResultSet;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 18:09:02 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContractVOImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }


    /**
     * Returns the variable value for buyerNameBind.
     * @return variable value for buyerNameBind
     */
    public String getbuyerNameBind() {
        return (String)ensureVariableManager().getVariableValue("buyerNameBind");
    }

    /**
     * Sets <code>value</code> for variable buyerNameBind.
     * @param value value to bind as buyerNameBind
     */
    public void setbuyerNameBind(String value) {
        ensureVariableManager().setVariableValue("buyerNameBind", value);
    }

    /**
     * Returns the variable value for seasonBind.
     * @return variable value for seasonBind
     */
    public String getseasonBind() {
        return (String)ensureVariableManager().getVariableValue("seasonBind");
    }

    /**
     * Sets <code>value</code> for variable seasonBind.
     * @param value value to bind as seasonBind
     */
    public void setseasonBind(String value) {
        ensureVariableManager().setVariableValue("seasonBind", value);
    }

    /**
     * Returns the variable value for ORG_ID.
     * @return variable value for ORG_ID
     */
    public Number getORG_ID() {
        return (Number)ensureVariableManager().getVariableValue("ORG_ID");
    }

    /**
     * Sets <code>value</code> for variable ORG_ID.
     * @param value value to bind as ORG_ID
     */
    public void setORG_ID(Number value) {
        ensureVariableManager().setVariableValue("ORG_ID", value);
    }
}
