package mnj.ont.model.lov.views;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 11 12:37:48 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExportLCVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExportLCVOImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    /**
     * Returns the variable value for exportLcBind.
     * @return variable value for exportLcBind
     */
    public String getexportLcBind() {
        return (String)ensureVariableManager().getVariableValue("exportLcBind");
    }

    /**
     * Sets <code>value</code> for variable exportLcBind.
     * @param value value to bind as exportLcBind
     */
    public void setexportLcBind(String value) {
        ensureVariableManager().setVariableValue("exportLcBind", value);
    }

    /**
     * Returns the variable value for buyerBind.
     * @return variable value for buyerBind
     */
    public String getbuyerBind() {
        return (String)ensureVariableManager().getVariableValue("buyerBind");
    }

    /**
     * Sets <code>value</code> for variable buyerBind.
     * @param value value to bind as buyerBind
     */
    public void setbuyerBind(String value) {
        ensureVariableManager().setVariableValue("buyerBind", value);
    }

    /**
     * Returns the variable value for seasonBind.
     * @return variable value for seasonBind
     */
    public String getseasonBind() {
        return (String)ensureVariableManager().getVariableValue("seasonBind");
    }

    /**
     * Sets <code>value</code> for variable seasonBind.
     * @param value value to bind as seasonBind
     */
    public void setseasonBind(String value) {
        ensureVariableManager().setVariableValue("seasonBind", value);
    }
}
