package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 09 13:24:18 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ShipmentModeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ShipmentModeVOImpl() {
    }
}
