package mnj.ont.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 14:50:20 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IncoTermVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IncoTermVOImpl() {
    }
}
