package mnj.ont.model.services.client;

import mnj.ont.model.services.common.MainAM;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 04 17:20:49 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAMClient extends ApplicationModuleImpl implements MainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MainAMClient() {
    }


    public void populateLines1(String OrgId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateLines1",new String [] {"java.lang.String"},new Object[] {OrgId});
        return;
    }

    public void populateLines(Row poprow) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateLines",new String [] {"oracle.jbo.Row"},new Object[] {poprow});
        return;
    }

    public String getPopulateValue(Row r, String columnName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPopulateValue",new String [] {"oracle.jbo.Row","java.lang.String"},new Object[] {r, columnName});
        return (String)_ret;
    }

    public String getOrgId() {
        Object _ret = this.riInvokeExportedMethod(this,"getOrgId",null,null);
        return (String)_ret;
    }

    public Row createBPOLines() {
        Object _ret = this.riInvokeExportedMethod(this,"createBPOLines",null,null);
        return (Row)_ret;
    }

    public void callFetch() {
        Object _ret = this.riInvokeExportedMethod(this,"callFetch",null,null);
        return;
    }

    public void popupSelectActionListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"popupSelectActionListener",null,null);
        return;
    }

    public void popupDeselectActionListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"popupDeselectActionListener",null,null);
        return;
    }

    public void fetchLines() {
        Object _ret = this.riInvokeExportedMethod(this,"fetchLines",null,null);
        return;
    }

    public void saveActionButton() {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveActionButton",null,null);
        return;
    }

    public void testDate() {
        Object _ret = this.riInvokeExportedMethod(this,"testDate",null,null);
        return;
    }

    public void headerExecute() {
        Object _ret = this.riInvokeExportedMethod(this,"headerExecute",null,null);
        return;
    }

    public void copyDocument() {
        Object _ret = this.riInvokeExportedMethod(this,"copyDocument",null,null);
        return;
    }

    public void amendmentAction() {
        Object _ret =
            this.riInvokeExportedMethod(this,"amendmentAction",null,null);
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }
}
