package mnj.ont.model.popup.views.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 06 12:01:47 BDT 2017
// ---------------------------------------------------------------------
public interface FillLinesVO extends ViewObject {
    void setendDate(Date value);

    void setstartDate(Date value);
}
