package mnj.ont.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 01 20:25:51 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CiHeadersEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ExpCiHeaderId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getExpCiHeaderId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setExpCiHeaderId((Number)value);
            }
        }
        ,
        OrgName {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getOrgName();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setOrgName((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getBuyerId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Season {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getSeason();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        InvoiceDate {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getInvoiceDate();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setInvoiceDate((Date)value);
            }
        }
        ,
        ContractLcNumber {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getContractLcNumber();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setContractLcNumber((String)value);
            }
        }
        ,
        ContractLcDate {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getContractLcDate();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setContractLcDate((Date)value);
            }
        }
        ,
        ExportLcNo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getExportLcNo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setExportLcNo((String)value);
            }
        }
        ,
        ExportLcDate {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getExportLcDate();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setExportLcDate((Date)value);
            }
        }
        ,
        ExpNo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getExpNo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setExpNo((String)value);
            }
        }
        ,
        ExpDate {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getExpDate();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setExpDate((Date)value);
            }
        }
        ,
        CommissionPercentage {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCommissionPercentage();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setCommissionPercentage((String)value);
            }
        }
        ,
        VersionNo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getVersionNo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        OrgId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute16();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute17();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute18();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute19();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttribute20();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        AttributeNum1 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum1();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum1((Number)value);
            }
        }
        ,
        AttributeNum2 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum2();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum2((Number)value);
            }
        }
        ,
        AttributeNum3 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum3();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum3((Number)value);
            }
        }
        ,
        AttributeNum4 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum4();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum4((Number)value);
            }
        }
        ,
        AttributeNum5 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum5();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum5((Number)value);
            }
        }
        ,
        AttributeNum6 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum6();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum6((Number)value);
            }
        }
        ,
        AttributeNum7 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum7();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum7((Number)value);
            }
        }
        ,
        AttributeNum8 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum8();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum8((Number)value);
            }
        }
        ,
        AttributeNum9 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum9();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum9((Number)value);
            }
        }
        ,
        AttributeNum10 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeNum10();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeNum10((Number)value);
            }
        }
        ,
        AttributeDate1 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeDate1();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeDate1((Date)value);
            }
        }
        ,
        AttributeDate2 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeDate2();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeDate2((Date)value);
            }
        }
        ,
        AttributeDate3 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeDate3();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeDate3((Date)value);
            }
        }
        ,
        AttributeDate4 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeDate4();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeDate4((Date)value);
            }
        }
        ,
        AttributeDate5 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getAttributeDate5();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeDate5((Date)value);
            }
        }
        ,
        InvoiceAmount {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getInvoiceAmount();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setInvoiceAmount((Number)value);
            }
        }
        ,
        ManufacturerName {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getManufacturerName();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setManufacturerName((String)value);
            }
        }
        ,
        TotalContractValue {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getTotalContractValue();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setTotalContractValue((String)value);
            }
        }
        ,
        NegotiationBank {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getNegotiationBank();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setNegotiationBank((String)value);
            }
        }
        ,
        BankBranch {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getBankBranch();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setBankBranch((String)value);
            }
        }
        ,
        BankAddress {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getBankAddress();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setBankAddress((String)value);
            }
        }
        ,
        TotalExportedValue {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getTotalExportedValue();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setTotalExportedValue((Number)value);
            }
        }
        ,
        TotalGrossWeight {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getTotalGrossWeight();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setTotalGrossWeight((Number)value);
            }
        }
        ,
        TotalNetWt {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getTotalNetWt();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setTotalNetWt((Number)value);
            }
        }
        ,
        TotalNetNetWt {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getTotalNetNetWt();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setTotalNetNetWt((Number)value);
            }
        }
        ,
        TotalCartonQty {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getTotalCartonQty();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setTotalCartonQty((Number)value);
            }
        }
        ,
        Consignee {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getConsignee();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setConsignee((String)value);
            }
        }
        ,
        Currency {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCurrency();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        DocNo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getDocNo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setDocNo((Number)value);
            }
        }
        ,
        ConsigneeAddress {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getConsigneeAddress();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setConsigneeAddress((String)value);
            }
        }
        ,
        NotifyTo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getNotifyTo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setNotifyTo((String)value);
            }
        }
        ,
        NotifyAddress {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getNotifyAddress();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setNotifyAddress((String)value);
            }
        }
        ,
        ShipTo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getShipTo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setShipTo((String)value);
            }
        }
        ,
        ShipToAddress {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getShipToAddress();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setShipToAddress((String)value);
            }
        }
        ,
        TotalCbmM3 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getTotalCbmM3();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setTotalCbmM3((Number)value);
            }
        }
        ,
        BillTo {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getBillTo();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setBillTo((Number)value);
            }
        }
        ,
        CustAccountId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCustAccountId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setCustAccountId((Number)value);
            }
        }
        ,
        CustAcctSiteId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCustAcctSiteId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setCustAcctSiteId((Number)value);
            }
        }
        ,
        BillCustomerId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getBillCustomerId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setBillCustomerId((Number)value);
            }
        }
        ,
        BillAddressId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getBillAddressId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setBillAddressId((Number)value);
            }
        }
        ,
        ShipAddressId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getShipAddressId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setShipAddressId((Number)value);
            }
        }
        ,
        ShipCustomerId {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getShipCustomerId();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setShipCustomerId((Number)value);
            }
        }
        ,
        BillToAddress {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getBillToAddress();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setBillToAddress((String)value);
            }
        }
        ,
        InvoiceDate2 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getInvoiceDate2();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setInvoiceDate2((Date)value);
            }
        }
        ,
        CiLines {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCiLines();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CiLines2 {
            public Object get(CiHeadersEOImpl obj) {
                return obj.getCiLines2();
            }

            public void put(CiHeadersEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CiHeadersEOImpl object);

        public abstract void put(CiHeadersEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EXPCIHEADERID = AttributesEnum.ExpCiHeaderId.index();
    public static final int ORGNAME = AttributesEnum.OrgName.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int CONTRACTLCNUMBER = AttributesEnum.ContractLcNumber.index();
    public static final int CONTRACTLCDATE = AttributesEnum.ContractLcDate.index();
    public static final int EXPORTLCNO = AttributesEnum.ExportLcNo.index();
    public static final int EXPORTLCDATE = AttributesEnum.ExportLcDate.index();
    public static final int EXPNO = AttributesEnum.ExpNo.index();
    public static final int EXPDATE = AttributesEnum.ExpDate.index();
    public static final int COMMISSIONPERCENTAGE = AttributesEnum.CommissionPercentage.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTENUM1 = AttributesEnum.AttributeNum1.index();
    public static final int ATTRIBUTENUM2 = AttributesEnum.AttributeNum2.index();
    public static final int ATTRIBUTENUM3 = AttributesEnum.AttributeNum3.index();
    public static final int ATTRIBUTENUM4 = AttributesEnum.AttributeNum4.index();
    public static final int ATTRIBUTENUM5 = AttributesEnum.AttributeNum5.index();
    public static final int ATTRIBUTENUM6 = AttributesEnum.AttributeNum6.index();
    public static final int ATTRIBUTENUM7 = AttributesEnum.AttributeNum7.index();
    public static final int ATTRIBUTENUM8 = AttributesEnum.AttributeNum8.index();
    public static final int ATTRIBUTENUM9 = AttributesEnum.AttributeNum9.index();
    public static final int ATTRIBUTENUM10 = AttributesEnum.AttributeNum10.index();
    public static final int ATTRIBUTEDATE1 = AttributesEnum.AttributeDate1.index();
    public static final int ATTRIBUTEDATE2 = AttributesEnum.AttributeDate2.index();
    public static final int ATTRIBUTEDATE3 = AttributesEnum.AttributeDate3.index();
    public static final int ATTRIBUTEDATE4 = AttributesEnum.AttributeDate4.index();
    public static final int ATTRIBUTEDATE5 = AttributesEnum.AttributeDate5.index();
    public static final int INVOICEAMOUNT = AttributesEnum.InvoiceAmount.index();
    public static final int MANUFACTURERNAME = AttributesEnum.ManufacturerName.index();
    public static final int TOTALCONTRACTVALUE = AttributesEnum.TotalContractValue.index();
    public static final int NEGOTIATIONBANK = AttributesEnum.NegotiationBank.index();
    public static final int BANKBRANCH = AttributesEnum.BankBranch.index();
    public static final int BANKADDRESS = AttributesEnum.BankAddress.index();
    public static final int TOTALEXPORTEDVALUE = AttributesEnum.TotalExportedValue.index();
    public static final int TOTALGROSSWEIGHT = AttributesEnum.TotalGrossWeight.index();
    public static final int TOTALNETWT = AttributesEnum.TotalNetWt.index();
    public static final int TOTALNETNETWT = AttributesEnum.TotalNetNetWt.index();
    public static final int TOTALCARTONQTY = AttributesEnum.TotalCartonQty.index();
    public static final int CONSIGNEE = AttributesEnum.Consignee.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int DOCNO = AttributesEnum.DocNo.index();
    public static final int CONSIGNEEADDRESS = AttributesEnum.ConsigneeAddress.index();
    public static final int NOTIFYTO = AttributesEnum.NotifyTo.index();
    public static final int NOTIFYADDRESS = AttributesEnum.NotifyAddress.index();
    public static final int SHIPTO = AttributesEnum.ShipTo.index();
    public static final int SHIPTOADDRESS = AttributesEnum.ShipToAddress.index();
    public static final int TOTALCBMM3 = AttributesEnum.TotalCbmM3.index();
    public static final int BILLTO = AttributesEnum.BillTo.index();
    public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
    public static final int CUSTACCTSITEID = AttributesEnum.CustAcctSiteId.index();
    public static final int BILLCUSTOMERID = AttributesEnum.BillCustomerId.index();
    public static final int BILLADDRESSID = AttributesEnum.BillAddressId.index();
    public static final int SHIPADDRESSID = AttributesEnum.ShipAddressId.index();
    public static final int SHIPCUSTOMERID = AttributesEnum.ShipCustomerId.index();
    public static final int BILLTOADDRESS = AttributesEnum.BillToAddress.index();
    public static final int INVOICEDATE2 = AttributesEnum.InvoiceDate2.index();
    public static final int CILINES = AttributesEnum.CiLines.index();
    public static final int CILINES2 = AttributesEnum.CiLines2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CiHeadersEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.CiHeadersEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ExpCiHeaderId, using the alias name ExpCiHeaderId.
     * @return the ExpCiHeaderId
     */
    public Number getExpCiHeaderId() {
        return (Number)getAttributeInternal(EXPCIHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpCiHeaderId.
     * @param value value to set the ExpCiHeaderId
     */
    public void setExpCiHeaderId(Number value) {
        setAttributeInternal(EXPCIHEADERID, value);
    }

    /**
     * Gets the attribute value for OrgName, using the alias name OrgName.
     * @return the OrgName
     */
    public String getOrgName() {
        return (String)getAttributeInternal(ORGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgName.
     * @param value value to set the OrgName
     */
    public void setOrgName(String value) {
        setAttributeInternal(ORGNAME, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for InvoiceNo, using the alias name InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String)getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceNo.
     * @param value value to set the InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for InvoiceDate, using the alias name InvoiceDate.
     * @return the InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date)getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceDate.
     * @param value value to set the InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for ContractLcNumber, using the alias name ContractLcNumber.
     * @return the ContractLcNumber
     */
    public String getContractLcNumber() {
        return (String)getAttributeInternal(CONTRACTLCNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractLcNumber.
     * @param value value to set the ContractLcNumber
     */
    public void setContractLcNumber(String value) {
        setAttributeInternal(CONTRACTLCNUMBER, value);
    }

    /**
     * Gets the attribute value for ContractLcDate, using the alias name ContractLcDate.
     * @return the ContractLcDate
     */
    public Date getContractLcDate() {
        return (Date)getAttributeInternal(CONTRACTLCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractLcDate.
     * @param value value to set the ContractLcDate
     */
    public void setContractLcDate(Date value) {
        setAttributeInternal(CONTRACTLCDATE, value);
    }

    /**
     * Gets the attribute value for ExportLcNo, using the alias name ExportLcNo.
     * @return the ExportLcNo
     */
    public String getExportLcNo() {
        return (String)getAttributeInternal(EXPORTLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcNo.
     * @param value value to set the ExportLcNo
     */
    public void setExportLcNo(String value) {
        setAttributeInternal(EXPORTLCNO, value);
    }

    /**
     * Gets the attribute value for ExportLcDate, using the alias name ExportLcDate.
     * @return the ExportLcDate
     */
    public Date getExportLcDate() {
        return (Date)getAttributeInternal(EXPORTLCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcDate.
     * @param value value to set the ExportLcDate
     */
    public void setExportLcDate(Date value) {
        setAttributeInternal(EXPORTLCDATE, value);
    }

    /**
     * Gets the attribute value for ExpNo, using the alias name ExpNo.
     * @return the ExpNo
     */
    public String getExpNo() {
        return (String)getAttributeInternal(EXPNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpNo.
     * @param value value to set the ExpNo
     */
    public void setExpNo(String value) {
        setAttributeInternal(EXPNO, value);
    }

    /**
     * Gets the attribute value for ExpDate, using the alias name ExpDate.
     * @return the ExpDate
     */
    public Date getExpDate() {
        return (Date)getAttributeInternal(EXPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpDate.
     * @param value value to set the ExpDate
     */
    public void setExpDate(Date value) {
        setAttributeInternal(EXPDATE, value);
    }

    /**
     * Gets the attribute value for CommissionPercentage, using the alias name CommissionPercentage.
     * @return the CommissionPercentage
     */
    public String getCommissionPercentage() {
        return (String)getAttributeInternal(COMMISSIONPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommissionPercentage.
     * @param value value to set the CommissionPercentage
     */
    public void setCommissionPercentage(String value) {
        setAttributeInternal(COMMISSIONPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number)getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNo.
     * @param value value to set the VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for AttributeNum1, using the alias name AttributeNum1.
     * @return the AttributeNum1
     */
    public Number getAttributeNum1() {
        return (Number)getAttributeInternal(ATTRIBUTENUM1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum1.
     * @param value value to set the AttributeNum1
     */
    public void setAttributeNum1(Number value) {
        setAttributeInternal(ATTRIBUTENUM1, value);
    }

    /**
     * Gets the attribute value for AttributeNum2, using the alias name AttributeNum2.
     * @return the AttributeNum2
     */
    public Number getAttributeNum2() {
        return (Number)getAttributeInternal(ATTRIBUTENUM2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum2.
     * @param value value to set the AttributeNum2
     */
    public void setAttributeNum2(Number value) {
        setAttributeInternal(ATTRIBUTENUM2, value);
    }

    /**
     * Gets the attribute value for AttributeNum3, using the alias name AttributeNum3.
     * @return the AttributeNum3
     */
    public Number getAttributeNum3() {
        return (Number)getAttributeInternal(ATTRIBUTENUM3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum3.
     * @param value value to set the AttributeNum3
     */
    public void setAttributeNum3(Number value) {
        setAttributeInternal(ATTRIBUTENUM3, value);
    }

    /**
     * Gets the attribute value for AttributeNum4, using the alias name AttributeNum4.
     * @return the AttributeNum4
     */
    public Number getAttributeNum4() {
        return (Number)getAttributeInternal(ATTRIBUTENUM4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum4.
     * @param value value to set the AttributeNum4
     */
    public void setAttributeNum4(Number value) {
        setAttributeInternal(ATTRIBUTENUM4, value);
    }

    /**
     * Gets the attribute value for AttributeNum5, using the alias name AttributeNum5.
     * @return the AttributeNum5
     */
    public Number getAttributeNum5() {
        return (Number)getAttributeInternal(ATTRIBUTENUM5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum5.
     * @param value value to set the AttributeNum5
     */
    public void setAttributeNum5(Number value) {
        setAttributeInternal(ATTRIBUTENUM5, value);
    }

    /**
     * Gets the attribute value for AttributeNum6, using the alias name AttributeNum6.
     * @return the AttributeNum6
     */
    public Number getAttributeNum6() {
        return (Number)getAttributeInternal(ATTRIBUTENUM6);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum6.
     * @param value value to set the AttributeNum6
     */
    public void setAttributeNum6(Number value) {
        setAttributeInternal(ATTRIBUTENUM6, value);
    }

    /**
     * Gets the attribute value for AttributeNum7, using the alias name AttributeNum7.
     * @return the AttributeNum7
     */
    public Number getAttributeNum7() {
        return (Number)getAttributeInternal(ATTRIBUTENUM7);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum7.
     * @param value value to set the AttributeNum7
     */
    public void setAttributeNum7(Number value) {
        setAttributeInternal(ATTRIBUTENUM7, value);
    }

    /**
     * Gets the attribute value for AttributeNum8, using the alias name AttributeNum8.
     * @return the AttributeNum8
     */
    public Number getAttributeNum8() {
        return (Number)getAttributeInternal(ATTRIBUTENUM8);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum8.
     * @param value value to set the AttributeNum8
     */
    public void setAttributeNum8(Number value) {
        setAttributeInternal(ATTRIBUTENUM8, value);
    }

    /**
     * Gets the attribute value for AttributeNum9, using the alias name AttributeNum9.
     * @return the AttributeNum9
     */
    public Number getAttributeNum9() {
        return (Number)getAttributeInternal(ATTRIBUTENUM9);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum9.
     * @param value value to set the AttributeNum9
     */
    public void setAttributeNum9(Number value) {
        setAttributeInternal(ATTRIBUTENUM9, value);
    }

    /**
     * Gets the attribute value for AttributeNum10, using the alias name AttributeNum10.
     * @return the AttributeNum10
     */
    public Number getAttributeNum10() {
        return (Number)getAttributeInternal(ATTRIBUTENUM10);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum10.
     * @param value value to set the AttributeNum10
     */
    public void setAttributeNum10(Number value) {
        setAttributeInternal(ATTRIBUTENUM10, value);
    }

    /**
     * Gets the attribute value for AttributeDate1, using the alias name AttributeDate1.
     * @return the AttributeDate1
     */
    public Date getAttributeDate1() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate1.
     * @param value value to set the AttributeDate1
     */
    public void setAttributeDate1(Date value) {
        setAttributeInternal(ATTRIBUTEDATE1, value);
    }

    /**
     * Gets the attribute value for AttributeDate2, using the alias name AttributeDate2.
     * @return the AttributeDate2
     */
    public Date getAttributeDate2() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate2.
     * @param value value to set the AttributeDate2
     */
    public void setAttributeDate2(Date value) {
        setAttributeInternal(ATTRIBUTEDATE2, value);
    }

    /**
     * Gets the attribute value for AttributeDate3, using the alias name AttributeDate3.
     * @return the AttributeDate3
     */
    public Date getAttributeDate3() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate3.
     * @param value value to set the AttributeDate3
     */
    public void setAttributeDate3(Date value) {
        setAttributeInternal(ATTRIBUTEDATE3, value);
    }

    /**
     * Gets the attribute value for AttributeDate4, using the alias name AttributeDate4.
     * @return the AttributeDate4
     */
    public Date getAttributeDate4() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate4.
     * @param value value to set the AttributeDate4
     */
    public void setAttributeDate4(Date value) {
        setAttributeInternal(ATTRIBUTEDATE4, value);
    }

    /**
     * Gets the attribute value for AttributeDate5, using the alias name AttributeDate5.
     * @return the AttributeDate5
     */
    public Date getAttributeDate5() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate5.
     * @param value value to set the AttributeDate5
     */
    public void setAttributeDate5(Date value) {
        setAttributeInternal(ATTRIBUTEDATE5, value);
    }

    /**
     * Gets the attribute value for InvoiceAmount, using the alias name InvoiceAmount.
     * @return the InvoiceAmount
     */
    public Number getInvoiceAmount() {
        return (Number)getAttributeInternal(INVOICEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceAmount.
     * @param value value to set the InvoiceAmount
     */
    public void setInvoiceAmount(Number value) {
        setAttributeInternal(INVOICEAMOUNT, value);
    }

    /**
     * Gets the attribute value for ManufacturerName, using the alias name ManufacturerName.
     * @return the ManufacturerName
     */
    public String getManufacturerName() {
        return (String)getAttributeInternal(MANUFACTURERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManufacturerName.
     * @param value value to set the ManufacturerName
     */
    public void setManufacturerName(String value) {
        setAttributeInternal(MANUFACTURERNAME, value);
    }

    /**
     * Gets the attribute value for TotalContractValue, using the alias name TotalContractValue.
     * @return the TotalContractValue
     */
    public String getTotalContractValue() {
        return (String)getAttributeInternal(TOTALCONTRACTVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalContractValue.
     * @param value value to set the TotalContractValue
     */
    public void setTotalContractValue(String value) {
        setAttributeInternal(TOTALCONTRACTVALUE, value);
    }

    /**
     * Gets the attribute value for NegotiationBank, using the alias name NegotiationBank.
     * @return the NegotiationBank
     */
    public String getNegotiationBank() {
        return (String)getAttributeInternal(NEGOTIATIONBANK);
    }

    /**
     * Sets <code>value</code> as the attribute value for NegotiationBank.
     * @param value value to set the NegotiationBank
     */
    public void setNegotiationBank(String value) {
        setAttributeInternal(NEGOTIATIONBANK, value);
    }

    /**
     * Gets the attribute value for BankBranch, using the alias name BankBranch.
     * @return the BankBranch
     */
    public String getBankBranch() {
        return (String)getAttributeInternal(BANKBRANCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankBranch.
     * @param value value to set the BankBranch
     */
    public void setBankBranch(String value) {
        setAttributeInternal(BANKBRANCH, value);
    }

    /**
     * Gets the attribute value for BankAddress, using the alias name BankAddress.
     * @return the BankAddress
     */
    public String getBankAddress() {
        return (String)getAttributeInternal(BANKADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankAddress.
     * @param value value to set the BankAddress
     */
    public void setBankAddress(String value) {
        setAttributeInternal(BANKADDRESS, value);
    }

    /**
     * Gets the attribute value for TotalExportedValue, using the alias name TotalExportedValue.
     * @return the TotalExportedValue
     */
    public Number getTotalExportedValue() {
        return (Number)getAttributeInternal(TOTALEXPORTEDVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalExportedValue.
     * @param value value to set the TotalExportedValue
     */
    public void setTotalExportedValue(Number value) {
        setAttributeInternal(TOTALEXPORTEDVALUE, value);
    }

    /**
     * Gets the attribute value for TotalGrossWeight, using the alias name TotalGrossWeight.
     * @return the TotalGrossWeight
     */
    public Number getTotalGrossWeight() {
        return (Number)getAttributeInternal(TOTALGROSSWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalGrossWeight.
     * @param value value to set the TotalGrossWeight
     */
    public void setTotalGrossWeight(Number value) {
        setAttributeInternal(TOTALGROSSWEIGHT, value);
    }

    /**
     * Gets the attribute value for TotalNetWt, using the alias name TotalNetWt.
     * @return the TotalNetWt
     */
    public Number getTotalNetWt() {
        return (Number)getAttributeInternal(TOTALNETWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalNetWt.
     * @param value value to set the TotalNetWt
     */
    public void setTotalNetWt(Number value) {
        setAttributeInternal(TOTALNETWT, value);
    }

    /**
     * Gets the attribute value for TotalNetNetWt, using the alias name TotalNetNetWt.
     * @return the TotalNetNetWt
     */
    public Number getTotalNetNetWt() {
        return (Number)getAttributeInternal(TOTALNETNETWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalNetNetWt.
     * @param value value to set the TotalNetNetWt
     */
    public void setTotalNetNetWt(Number value) {
        setAttributeInternal(TOTALNETNETWT, value);
    }

    /**
     * Gets the attribute value for TotalCartonQty, using the alias name TotalCartonQty.
     * @return the TotalCartonQty
     */
    public Number getTotalCartonQty() {
        return (Number)getAttributeInternal(TOTALCARTONQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalCartonQty.
     * @param value value to set the TotalCartonQty
     */
    public void setTotalCartonQty(Number value) {
        setAttributeInternal(TOTALCARTONQTY, value);
    }

    /**
     * Gets the attribute value for Consignee, using the alias name Consignee.
     * @return the Consignee
     */
    public String getConsignee() {
        return (String)getAttributeInternal(CONSIGNEE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Consignee.
     * @param value value to set the Consignee
     */
    public void setConsignee(String value) {
        setAttributeInternal(CONSIGNEE, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for DocNo, using the alias name DocNo.
     * @return the DocNo
     */
    public Number getDocNo() {
        return (Number)getAttributeInternal(DOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocNo.
     * @param value value to set the DocNo
     */
    public void setDocNo(Number value) {
        setAttributeInternal(DOCNO, value);
    }

    /**
     * Gets the attribute value for ConsigneeAddress, using the alias name ConsigneeAddress.
     * @return the ConsigneeAddress
     */
    public String getConsigneeAddress() {
        return (String)getAttributeInternal(CONSIGNEEADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConsigneeAddress.
     * @param value value to set the ConsigneeAddress
     */
    public void setConsigneeAddress(String value) {
        setAttributeInternal(CONSIGNEEADDRESS, value);
    }

    /**
     * Gets the attribute value for NotifyTo, using the alias name NotifyTo.
     * @return the NotifyTo
     */
    public String getNotifyTo() {
        return (String)getAttributeInternal(NOTIFYTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NotifyTo.
     * @param value value to set the NotifyTo
     */
    public void setNotifyTo(String value) {
        setAttributeInternal(NOTIFYTO, value);
    }

    /**
     * Gets the attribute value for NotifyAddress, using the alias name NotifyAddress.
     * @return the NotifyAddress
     */
    public String getNotifyAddress() {
        return (String)getAttributeInternal(NOTIFYADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NotifyAddress.
     * @param value value to set the NotifyAddress
     */
    public void setNotifyAddress(String value) {
        setAttributeInternal(NOTIFYADDRESS, value);
    }

    /**
     * Gets the attribute value for ShipTo, using the alias name ShipTo.
     * @return the ShipTo
     */
    public String getShipTo() {
        return (String)getAttributeInternal(SHIPTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipTo.
     * @param value value to set the ShipTo
     */
    public void setShipTo(String value) {
        setAttributeInternal(SHIPTO, value);
    }

    /**
     * Gets the attribute value for ShipToAddress, using the alias name ShipToAddress.
     * @return the ShipToAddress
     */
    public String getShipToAddress() {
        return (String)getAttributeInternal(SHIPTOADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToAddress.
     * @param value value to set the ShipToAddress
     */
    public void setShipToAddress(String value) {
        setAttributeInternal(SHIPTOADDRESS, value);
    }

    /**
     * Gets the attribute value for TotalCbmM3, using the alias name TotalCbmM3.
     * @return the TotalCbmM3
     */
    public Number getTotalCbmM3() {
        return (Number)getAttributeInternal(TOTALCBMM3);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalCbmM3.
     * @param value value to set the TotalCbmM3
     */
    public void setTotalCbmM3(Number value) {
        setAttributeInternal(TOTALCBMM3, value);
    }

    /**
     * Gets the attribute value for BillTo, using the alias name BillTo.
     * @return the BillTo
     */
    public Number getBillTo() {
        return (Number)getAttributeInternal(BILLTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillTo.
     * @param value value to set the BillTo
     */
    public void setBillTo(Number value) {
        setAttributeInternal(BILLTO, value);
    }

    /**
     * Gets the attribute value for CustAccountId, using the alias name CustAccountId.
     * @return the CustAccountId
     */
    public Number getCustAccountId() {
        return (Number)getAttributeInternal(CUSTACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustAccountId.
     * @param value value to set the CustAccountId
     */
    public void setCustAccountId(Number value) {
        setAttributeInternal(CUSTACCOUNTID, value);
    }

    /**
     * Gets the attribute value for CustAcctSiteId, using the alias name CustAcctSiteId.
     * @return the CustAcctSiteId
     */
    public Number getCustAcctSiteId() {
        return (Number)getAttributeInternal(CUSTACCTSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustAcctSiteId.
     * @param value value to set the CustAcctSiteId
     */
    public void setCustAcctSiteId(Number value) {
        setAttributeInternal(CUSTACCTSITEID, value);
    }

    /**
     * Gets the attribute value for BillCustomerId, using the alias name BillCustomerId.
     * @return the BillCustomerId
     */
    public Number getBillCustomerId() {
        return (Number)getAttributeInternal(BILLCUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillCustomerId.
     * @param value value to set the BillCustomerId
     */
    public void setBillCustomerId(Number value) {
        setAttributeInternal(BILLCUSTOMERID, value);
    }

    /**
     * Gets the attribute value for BillAddressId, using the alias name BillAddressId.
     * @return the BillAddressId
     */
    public Number getBillAddressId() {
        return (Number)getAttributeInternal(BILLADDRESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillAddressId.
     * @param value value to set the BillAddressId
     */
    public void setBillAddressId(Number value) {
        setAttributeInternal(BILLADDRESSID, value);
    }

    /**
     * Gets the attribute value for ShipAddressId, using the alias name ShipAddressId.
     * @return the ShipAddressId
     */
    public Number getShipAddressId() {
        return (Number)getAttributeInternal(SHIPADDRESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipAddressId.
     * @param value value to set the ShipAddressId
     */
    public void setShipAddressId(Number value) {
        setAttributeInternal(SHIPADDRESSID, value);
    }

    /**
     * Gets the attribute value for ShipCustomerId, using the alias name ShipCustomerId.
     * @return the ShipCustomerId
     */
    public Number getShipCustomerId() {
        return (Number)getAttributeInternal(SHIPCUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipCustomerId.
     * @param value value to set the ShipCustomerId
     */
    public void setShipCustomerId(Number value) {
        setAttributeInternal(SHIPCUSTOMERID, value);
    }

    /**
     * Gets the attribute value for BillToAddress, using the alias name BillToAddress.
     * @return the BillToAddress
     */
    public String getBillToAddress() {
        return (String)getAttributeInternal(BILLTOADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillToAddress.
     * @param value value to set the BillToAddress
     */
    public void setBillToAddress(String value) {
        setAttributeInternal(BILLTOADDRESS, value);
    }

    /**
     * Gets the attribute value for InvoiceDate2, using the alias name InvoiceDate2.
     * @return the InvoiceDate2
     */
    public Date getInvoiceDate2() {
        return (Date)getAttributeInternal(INVOICEDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceDate2.
     * @param value value to set the InvoiceDate2
     */
    public void setInvoiceDate2(Date value) {
        setAttributeInternal(INVOICEDATE2, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCiLines() {
        return (RowIterator)getAttributeInternal(CILINES);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCiLines2() {
        return (RowIterator)getAttributeInternal(CILINES2);
    }


    /**
     * @param expCiHeaderId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number expCiHeaderId) {
        return new Key(new Object[]{expCiHeaderId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("CUST_MNJ_ONT_FINISHPCKASSORT_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        this.setExpCiHeaderId(sVal);
        this.setVersionNo(new oracle.jbo.domain.Number(1));
     
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String user = (String)sessionScope.get("userId");
        
        
        if (DML_UPDATE == operation) {
            try {
                setLastUpdateDate((Date)Date.getCurrentDate());
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                   
            } catch (SQLException f) {
              ;
            }
        } else if (DML_INSERT == operation) {
            
            this.setDocNo(new oracle.jbo.domain.Number(getSrNoString()));
             System.out.println("    =========   ======  "+this.getDocNo());
            try {
                
                 setCreationDate((Date)Date.getCurrentDate());
                 setCreatedBy(new oracle.jbo.domain.Number(user));
                
             

            } catch (SQLException f) {
                ;
            }
        }
        
        super.doDML(operation, e);
    }
    
    public int getSrNoString() {
          int srno = 0;
        System.out.println("OK");
          String stmt = "BEGIN :1 := EXP_COM_INV_DOC_NO; end;";
          java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
          try {
              System.out.println("OK");
              cs.registerOutParameter(1, oracle.jdbc.OracleTypes.NUMBER);
              cs.execute();
              srno = cs.getInt(1);
              cs.close();
          } catch (Exception e) {
              System.out.println("OK..............");
              e.printStackTrace();
          }
          return srno;
    }
}
