package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 01 20:29:04 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CiLinesEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ExpCiLineId {
            public Object get(CiLinesEOImpl obj) {
                return obj.getExpCiLineId();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setExpCiLineId((Number)value);
            }
        }
        ,
        ExpCiHeaderId {
            public Object get(CiLinesEOImpl obj) {
                return obj.getExpCiHeaderId();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setExpCiHeaderId((Number)value);
            }
        }
        ,
        Style {
            public Object get(CiLinesEOImpl obj) {
                return obj.getStyle();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        OrderBpo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getOrderBpo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setOrderBpo((String)value);
            }
        }
        ,
        Dcpo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getDcpo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setDcpo((String)value);
            }
        }
        ,
        ArticleNo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getArticleNo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setArticleNo((String)value);
            }
        }
        ,
        ItemNo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getItemNo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setItemNo((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(CiLinesEOImpl obj) {
                return obj.getItemDescription();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        ShipQty {
            public Object get(CiLinesEOImpl obj) {
                return obj.getShipQty();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setShipQty((Number)value);
            }
        }
        ,
        Uom {
            public Object get(CiLinesEOImpl obj) {
                return obj.getUom();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        UnitPrice {
            public Object get(CiLinesEOImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        GoodsValue {
            public Object get(CiLinesEOImpl obj) {
                return obj.getGoodsValue();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setGoodsValue((Number)value);
            }
        }
        ,
        TradeDiscountCommission {
            public Object get(CiLinesEOImpl obj) {
                return obj.getTradeDiscountCommission();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setTradeDiscountCommission((Number)value);
            }
        }
        ,
        InvoiceValue {
            public Object get(CiLinesEOImpl obj) {
                return obj.getInvoiceValue();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setInvoiceValue((Number)value);
            }
        }
        ,
        IncoTerms {
            public Object get(CiLinesEOImpl obj) {
                return obj.getIncoTerms();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setIncoTerms((String)value);
            }
        }
        ,
        HtsCode {
            public Object get(CiLinesEOImpl obj) {
                return obj.getHtsCode();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setHtsCode((String)value);
            }
        }
        ,
        CartonNo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCartonNo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCartonNo((String)value);
            }
        }
        ,
        CartonQuantity {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCartonQuantity();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCartonQuantity((Number)value);
            }
        }
        ,
        NetNetWeight {
            public Object get(CiLinesEOImpl obj) {
                return obj.getNetNetWeight();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setNetNetWeight((Number)value);
            }
        }
        ,
        NetWeight {
            public Object get(CiLinesEOImpl obj) {
                return obj.getNetWeight();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setNetWeight((Number)value);
            }
        }
        ,
        GrossWeight {
            public Object get(CiLinesEOImpl obj) {
                return obj.getGrossWeight();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setGrossWeight((Number)value);
            }
        }
        ,
        CbmM3 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCbmM3();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCbmM3((String)value);
            }
        }
        ,
        ExcessShortQty {
            public Object get(CiLinesEOImpl obj) {
                return obj.getExcessShortQty();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setExcessShortQty((Number)value);
            }
        }
        ,
        PercExcessShortQty {
            public Object get(CiLinesEOImpl obj) {
                return obj.getPercExcessShortQty();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setPercExcessShortQty((String)value);
            }
        }
        ,
        ShipmentMode {
            public Object get(CiLinesEOImpl obj) {
                return obj.getShipmentMode();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setShipmentMode((String)value);
            }
        }
        ,
        FreightCharge {
            public Object get(CiLinesEOImpl obj) {
                return obj.getFreightCharge();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setFreightCharge((Number)value);
            }
        }
        ,
        VersionNo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getVersionNo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(CiLinesEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        OrgId {
            public Object get(CiLinesEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CiLinesEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CiLinesEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CiLinesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute16();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute17();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute18();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute19();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttribute20();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        AttributeNum1 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum1();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum1((Number)value);
            }
        }
        ,
        AttributeNum2 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum2();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum2((Number)value);
            }
        }
        ,
        AttributeNum3 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum3();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum3((Number)value);
            }
        }
        ,
        AttributeNum4 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum4();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum4((Number)value);
            }
        }
        ,
        AttributeNum5 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum5();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum5((Number)value);
            }
        }
        ,
        AttributeNum6 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum6();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum6((Number)value);
            }
        }
        ,
        AttributeNum7 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum7();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum7((Number)value);
            }
        }
        ,
        AttributeNum8 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum8();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum8((Number)value);
            }
        }
        ,
        AttributeNum9 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum9();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum9((Number)value);
            }
        }
        ,
        AttributeNum10 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeNum10();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeNum10((Number)value);
            }
        }
        ,
        AttributeDate1 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeDate1();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeDate1((Date)value);
            }
        }
        ,
        AttributeDate2 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeDate2();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeDate2((Date)value);
            }
        }
        ,
        AttributeDate3 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeDate3();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeDate3((Date)value);
            }
        }
        ,
        AttributeDate4 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeDate4();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeDate4((Date)value);
            }
        }
        ,
        AttributeDate5 {
            public Object get(CiLinesEOImpl obj) {
                return obj.getAttributeDate5();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setAttributeDate5((Date)value);
            }
        }
        ,
        IncoTermsValue {
            public Object get(CiLinesEOImpl obj) {
                return obj.getIncoTermsValue();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setIncoTermsValue((String)value);
            }
        }
        ,
        ShipmentType {
            public Object get(CiLinesEOImpl obj) {
                return obj.getShipmentType();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setShipmentType((String)value);
            }
        }
        ,
        ChargableGrossWeight {
            public Object get(CiLinesEOImpl obj) {
                return obj.getChargableGrossWeight();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setChargableGrossWeight((String)value);
            }
        }
        ,
        TotalCbm {
            public Object get(CiLinesEOImpl obj) {
                return obj.getTotalCbm();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setTotalCbm((Number)value);
            }
        }
        ,
        ShortExcessPer {
            public Object get(CiLinesEOImpl obj) {
                return obj.getShortExcessPer();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setShortExcessPer((Number)value);
            }
        }
        ,
        ShortExcessQty {
            public Object get(CiLinesEOImpl obj) {
                return obj.getShortExcessQty();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setShortExcessQty((Number)value);
            }
        }
        ,
        PackListNo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getPackListNo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setPackListNo((Number)value);
            }
        }
        ,
        Country {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCountry();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        TransportationMode {
            public Object get(CiLinesEOImpl obj) {
                return obj.getTransportationMode();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setTransportationMode((String)value);
            }
        }
        ,
        Currency {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCurrency();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        OrderItemId {
            public Object get(CiLinesEOImpl obj) {
                return obj.getOrderItemId();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setOrderItemId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(CiLinesEOImpl obj) {
                return obj.getItemCode();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ItemName {
            public Object get(CiLinesEOImpl obj) {
                return obj.getItemName();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setItemName((String)value);
            }
        }
        ,
        FinalUnitPrice {
            public Object get(CiLinesEOImpl obj) {
                return obj.getFinalUnitPrice();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setFinalUnitPrice((Number)value);
            }
        }
        ,
        ChildStyleNo {
            public Object get(CiLinesEOImpl obj) {
                return obj.getChildStyleNo();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setChildStyleNo((String)value);
            }
        }
        ,
        HangerCost {
            public Object get(CiLinesEOImpl obj) {
                return obj.getHangerCost();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setHangerCost((Number)value);
            }
        }
        ,
        HangerStyle {
            public Object get(CiLinesEOImpl obj) {
                return obj.getHangerStyle();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setHangerStyle((String)value);
            }
        }
        ,
        SizerCost {
            public Object get(CiLinesEOImpl obj) {
                return obj.getSizerCost();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setSizerCost((Number)value);
            }
        }
        ,
        SizerStyle {
            public Object get(CiLinesEOImpl obj) {
                return obj.getSizerStyle();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setSizerStyle((String)value);
            }
        }
        ,
        BpoId {
            public Object get(CiLinesEOImpl obj) {
                return obj.getBpoId();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        CiHeaders {
            public Object get(CiLinesEOImpl obj) {
                return obj.getCiHeaders();
            }

            public void put(CiLinesEOImpl obj, Object value) {
                obj.setCiHeaders((CiHeadersEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CiLinesEOImpl object);

        public abstract void put(CiLinesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EXPCILINEID = AttributesEnum.ExpCiLineId.index();
    public static final int EXPCIHEADERID = AttributesEnum.ExpCiHeaderId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int ORDERBPO = AttributesEnum.OrderBpo.index();
    public static final int DCPO = AttributesEnum.Dcpo.index();
    public static final int ARTICLENO = AttributesEnum.ArticleNo.index();
    public static final int ITEMNO = AttributesEnum.ItemNo.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int SHIPQTY = AttributesEnum.ShipQty.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int GOODSVALUE = AttributesEnum.GoodsValue.index();
    public static final int TRADEDISCOUNTCOMMISSION = AttributesEnum.TradeDiscountCommission.index();
    public static final int INVOICEVALUE = AttributesEnum.InvoiceValue.index();
    public static final int INCOTERMS = AttributesEnum.IncoTerms.index();
    public static final int HTSCODE = AttributesEnum.HtsCode.index();
    public static final int CARTONNO = AttributesEnum.CartonNo.index();
    public static final int CARTONQUANTITY = AttributesEnum.CartonQuantity.index();
    public static final int NETNETWEIGHT = AttributesEnum.NetNetWeight.index();
    public static final int NETWEIGHT = AttributesEnum.NetWeight.index();
    public static final int GROSSWEIGHT = AttributesEnum.GrossWeight.index();
    public static final int CBMM3 = AttributesEnum.CbmM3.index();
    public static final int EXCESSSHORTQTY = AttributesEnum.ExcessShortQty.index();
    public static final int PERCEXCESSSHORTQTY = AttributesEnum.PercExcessShortQty.index();
    public static final int SHIPMENTMODE = AttributesEnum.ShipmentMode.index();
    public static final int FREIGHTCHARGE = AttributesEnum.FreightCharge.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTENUM1 = AttributesEnum.AttributeNum1.index();
    public static final int ATTRIBUTENUM2 = AttributesEnum.AttributeNum2.index();
    public static final int ATTRIBUTENUM3 = AttributesEnum.AttributeNum3.index();
    public static final int ATTRIBUTENUM4 = AttributesEnum.AttributeNum4.index();
    public static final int ATTRIBUTENUM5 = AttributesEnum.AttributeNum5.index();
    public static final int ATTRIBUTENUM6 = AttributesEnum.AttributeNum6.index();
    public static final int ATTRIBUTENUM7 = AttributesEnum.AttributeNum7.index();
    public static final int ATTRIBUTENUM8 = AttributesEnum.AttributeNum8.index();
    public static final int ATTRIBUTENUM9 = AttributesEnum.AttributeNum9.index();
    public static final int ATTRIBUTENUM10 = AttributesEnum.AttributeNum10.index();
    public static final int ATTRIBUTEDATE1 = AttributesEnum.AttributeDate1.index();
    public static final int ATTRIBUTEDATE2 = AttributesEnum.AttributeDate2.index();
    public static final int ATTRIBUTEDATE3 = AttributesEnum.AttributeDate3.index();
    public static final int ATTRIBUTEDATE4 = AttributesEnum.AttributeDate4.index();
    public static final int ATTRIBUTEDATE5 = AttributesEnum.AttributeDate5.index();
    public static final int INCOTERMSVALUE = AttributesEnum.IncoTermsValue.index();
    public static final int SHIPMENTTYPE = AttributesEnum.ShipmentType.index();
    public static final int CHARGABLEGROSSWEIGHT = AttributesEnum.ChargableGrossWeight.index();
    public static final int TOTALCBM = AttributesEnum.TotalCbm.index();
    public static final int SHORTEXCESSPER = AttributesEnum.ShortExcessPer.index();
    public static final int SHORTEXCESSQTY = AttributesEnum.ShortExcessQty.index();
    public static final int PACKLISTNO = AttributesEnum.PackListNo.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int TRANSPORTATIONMODE = AttributesEnum.TransportationMode.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int ORDERITEMID = AttributesEnum.OrderItemId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMNAME = AttributesEnum.ItemName.index();
    public static final int FINALUNITPRICE = AttributesEnum.FinalUnitPrice.index();
    public static final int CHILDSTYLENO = AttributesEnum.ChildStyleNo.index();
    public static final int HANGERCOST = AttributesEnum.HangerCost.index();
    public static final int HANGERSTYLE = AttributesEnum.HangerStyle.index();
    public static final int SIZERCOST = AttributesEnum.SizerCost.index();
    public static final int SIZERSTYLE = AttributesEnum.SizerStyle.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int CIHEADERS = AttributesEnum.CiHeaders.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CiLinesEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.CiLinesEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ExpCiLineId, using the alias name ExpCiLineId.
     * @return the ExpCiLineId
     */
    public Number getExpCiLineId() {
        return (Number)getAttributeInternal(EXPCILINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpCiLineId.
     * @param value value to set the ExpCiLineId
     */
    public void setExpCiLineId(Number value) {
        setAttributeInternal(EXPCILINEID, value);
    }

    /**
     * Gets the attribute value for ExpCiHeaderId, using the alias name ExpCiHeaderId.
     * @return the ExpCiHeaderId
     */
    public Number getExpCiHeaderId() {
        return (Number)getAttributeInternal(EXPCIHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpCiHeaderId.
     * @param value value to set the ExpCiHeaderId
     */
    public void setExpCiHeaderId(Number value) {
        setAttributeInternal(EXPCIHEADERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for OrderBpo, using the alias name OrderBpo.
     * @return the OrderBpo
     */
    public String getOrderBpo() {
        return (String)getAttributeInternal(ORDERBPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderBpo.
     * @param value value to set the OrderBpo
     */
    public void setOrderBpo(String value) {
        setAttributeInternal(ORDERBPO, value);
    }

    /**
     * Gets the attribute value for Dcpo, using the alias name Dcpo.
     * @return the Dcpo
     */
    public String getDcpo() {
        return (String)getAttributeInternal(DCPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dcpo.
     * @param value value to set the Dcpo
     */
    public void setDcpo(String value) {
        setAttributeInternal(DCPO, value);
    }

    /**
     * Gets the attribute value for ArticleNo, using the alias name ArticleNo.
     * @return the ArticleNo
     */
    public String getArticleNo() {
        return (String)getAttributeInternal(ARTICLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArticleNo.
     * @param value value to set the ArticleNo
     */
    public void setArticleNo(String value) {
        setAttributeInternal(ARTICLENO, value);
    }

    /**
     * Gets the attribute value for ItemNo, using the alias name ItemNo.
     * @return the ItemNo
     */
    public String getItemNo() {
        return (String)getAttributeInternal(ITEMNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemNo.
     * @param value value to set the ItemNo
     */
    public void setItemNo(String value) {
        setAttributeInternal(ITEMNO, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ShipQty, using the alias name ShipQty.
     * @return the ShipQty
     */
    public Number getShipQty() {
        return (Number)getAttributeInternal(SHIPQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipQty.
     * @param value value to set the ShipQty
     */
    public void setShipQty(Number value) {
        setAttributeInternal(SHIPQTY, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for UnitPrice, using the alias name UnitPrice.
     * @return the UnitPrice
     */
    public Number getUnitPrice() {
        return (Number)getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPrice.
     * @param value value to set the UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for GoodsValue, using the alias name GoodsValue.
     * @return the GoodsValue
     */
    public Number getGoodsValue() {
        return (Number)getAttributeInternal(GOODSVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GoodsValue.
     * @param value value to set the GoodsValue
     */
    public void setGoodsValue(Number value) {
        setAttributeInternal(GOODSVALUE, value);
    }

    /**
     * Gets the attribute value for TradeDiscountCommission, using the alias name TradeDiscountCommission.
     * @return the TradeDiscountCommission
     */
    public Number getTradeDiscountCommission() {
        return (Number)getAttributeInternal(TRADEDISCOUNTCOMMISSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for TradeDiscountCommission.
     * @param value value to set the TradeDiscountCommission
     */
    public void setTradeDiscountCommission(Number value) {
        setAttributeInternal(TRADEDISCOUNTCOMMISSION, value);
    }

    /**
     * Gets the attribute value for InvoiceValue, using the alias name InvoiceValue.
     * @return the InvoiceValue
     */
    public Number getInvoiceValue() {
        return (Number)getAttributeInternal(INVOICEVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceValue.
     * @param value value to set the InvoiceValue
     */
    public void setInvoiceValue(Number value) {
        setAttributeInternal(INVOICEVALUE, value);
    }

    /**
     * Gets the attribute value for IncoTerms, using the alias name IncoTerms.
     * @return the IncoTerms
     */
    public String getIncoTerms() {
        return (String)getAttributeInternal(INCOTERMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncoTerms.
     * @param value value to set the IncoTerms
     */
    public void setIncoTerms(String value) {
        setAttributeInternal(INCOTERMS, value);
    }

    /**
     * Gets the attribute value for HtsCode, using the alias name HtsCode.
     * @return the HtsCode
     */
    public String getHtsCode() {
        return (String)getAttributeInternal(HTSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HtsCode.
     * @param value value to set the HtsCode
     */
    public void setHtsCode(String value) {
        setAttributeInternal(HTSCODE, value);
    }

    /**
     * Gets the attribute value for CartonNo, using the alias name CartonNo.
     * @return the CartonNo
     */
    public String getCartonNo() {
        return (String)getAttributeInternal(CARTONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CartonNo.
     * @param value value to set the CartonNo
     */
    public void setCartonNo(String value) {
        setAttributeInternal(CARTONNO, value);
    }

    /**
     * Gets the attribute value for CartonQuantity, using the alias name CartonQuantity.
     * @return the CartonQuantity
     */
    public Number getCartonQuantity() {
        return (Number)getAttributeInternal(CARTONQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CartonQuantity.
     * @param value value to set the CartonQuantity
     */
    public void setCartonQuantity(Number value) {
        setAttributeInternal(CARTONQUANTITY, value);
    }

    /**
     * Gets the attribute value for NetNetWeight, using the alias name NetNetWeight.
     * @return the NetNetWeight
     */
    public Number getNetNetWeight() {
        return (Number)getAttributeInternal(NETNETWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetNetWeight.
     * @param value value to set the NetNetWeight
     */
    public void setNetNetWeight(Number value) {
        setAttributeInternal(NETNETWEIGHT, value);
    }

    /**
     * Gets the attribute value for NetWeight, using the alias name NetWeight.
     * @return the NetWeight
     */
    public Number getNetWeight() {
        return (Number)getAttributeInternal(NETWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetWeight.
     * @param value value to set the NetWeight
     */
    public void setNetWeight(Number value) {
        setAttributeInternal(NETWEIGHT, value);
    }

    /**
     * Gets the attribute value for GrossWeight, using the alias name GrossWeight.
     * @return the GrossWeight
     */
    public Number getGrossWeight() {
        return (Number)getAttributeInternal(GROSSWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrossWeight.
     * @param value value to set the GrossWeight
     */
    public void setGrossWeight(Number value) {
        setAttributeInternal(GROSSWEIGHT, value);
    }

    /**
     * Gets the attribute value for CbmM3, using the alias name CbmM3.
     * @return the CbmM3
     */
    public String getCbmM3() {
        return (String)getAttributeInternal(CBMM3);
    }

    /**
     * Sets <code>value</code> as the attribute value for CbmM3.
     * @param value value to set the CbmM3
     */
    public void setCbmM3(String value) {
        setAttributeInternal(CBMM3, value);
    }

    /**
     * Gets the attribute value for ExcessShortQty, using the alias name ExcessShortQty.
     * @return the ExcessShortQty
     */
    public Number getExcessShortQty() {
        return (Number)getAttributeInternal(EXCESSSHORTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExcessShortQty.
     * @param value value to set the ExcessShortQty
     */
    public void setExcessShortQty(Number value) {
        setAttributeInternal(EXCESSSHORTQTY, value);
    }

    /**
     * Gets the attribute value for PercExcessShortQty, using the alias name PercExcessShortQty.
     * @return the PercExcessShortQty
     */
    public String getPercExcessShortQty() {
        return (String)getAttributeInternal(PERCEXCESSSHORTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PercExcessShortQty.
     * @param value value to set the PercExcessShortQty
     */
    public void setPercExcessShortQty(String value) {
        setAttributeInternal(PERCEXCESSSHORTQTY, value);
    }

    /**
     * Gets the attribute value for ShipmentMode, using the alias name ShipmentMode.
     * @return the ShipmentMode
     */
    public String getShipmentMode() {
        return (String)getAttributeInternal(SHIPMENTMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentMode.
     * @param value value to set the ShipmentMode
     */
    public void setShipmentMode(String value) {
        setAttributeInternal(SHIPMENTMODE, value);
    }

    /**
     * Gets the attribute value for FreightCharge, using the alias name FreightCharge.
     * @return the FreightCharge
     */
    public Number getFreightCharge() {
        return (Number)getAttributeInternal(FREIGHTCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FreightCharge.
     * @param value value to set the FreightCharge
     */
    public void setFreightCharge(Number value) {
        setAttributeInternal(FREIGHTCHARGE, value);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number)getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNo.
     * @param value value to set the VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for AttributeNum1, using the alias name AttributeNum1.
     * @return the AttributeNum1
     */
    public Number getAttributeNum1() {
        return (Number)getAttributeInternal(ATTRIBUTENUM1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum1.
     * @param value value to set the AttributeNum1
     */
    public void setAttributeNum1(Number value) {
        setAttributeInternal(ATTRIBUTENUM1, value);
    }

    /**
     * Gets the attribute value for AttributeNum2, using the alias name AttributeNum2.
     * @return the AttributeNum2
     */
    public Number getAttributeNum2() {
        return (Number)getAttributeInternal(ATTRIBUTENUM2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum2.
     * @param value value to set the AttributeNum2
     */
    public void setAttributeNum2(Number value) {
        setAttributeInternal(ATTRIBUTENUM2, value);
    }

    /**
     * Gets the attribute value for AttributeNum3, using the alias name AttributeNum3.
     * @return the AttributeNum3
     */
    public Number getAttributeNum3() {
        return (Number)getAttributeInternal(ATTRIBUTENUM3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum3.
     * @param value value to set the AttributeNum3
     */
    public void setAttributeNum3(Number value) {
        setAttributeInternal(ATTRIBUTENUM3, value);
    }

    /**
     * Gets the attribute value for AttributeNum4, using the alias name AttributeNum4.
     * @return the AttributeNum4
     */
    public Number getAttributeNum4() {
        return (Number)getAttributeInternal(ATTRIBUTENUM4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum4.
     * @param value value to set the AttributeNum4
     */
    public void setAttributeNum4(Number value) {
        setAttributeInternal(ATTRIBUTENUM4, value);
    }

    /**
     * Gets the attribute value for AttributeNum5, using the alias name AttributeNum5.
     * @return the AttributeNum5
     */
    public Number getAttributeNum5() {
        return (Number)getAttributeInternal(ATTRIBUTENUM5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum5.
     * @param value value to set the AttributeNum5
     */
    public void setAttributeNum5(Number value) {
        setAttributeInternal(ATTRIBUTENUM5, value);
    }

    /**
     * Gets the attribute value for AttributeNum6, using the alias name AttributeNum6.
     * @return the AttributeNum6
     */
    public Number getAttributeNum6() {
        return (Number)getAttributeInternal(ATTRIBUTENUM6);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum6.
     * @param value value to set the AttributeNum6
     */
    public void setAttributeNum6(Number value) {
        setAttributeInternal(ATTRIBUTENUM6, value);
    }

    /**
     * Gets the attribute value for AttributeNum7, using the alias name AttributeNum7.
     * @return the AttributeNum7
     */
    public Number getAttributeNum7() {
        return (Number)getAttributeInternal(ATTRIBUTENUM7);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum7.
     * @param value value to set the AttributeNum7
     */
    public void setAttributeNum7(Number value) {
        setAttributeInternal(ATTRIBUTENUM7, value);
    }

    /**
     * Gets the attribute value for AttributeNum8, using the alias name AttributeNum8.
     * @return the AttributeNum8
     */
    public Number getAttributeNum8() {
        return (Number)getAttributeInternal(ATTRIBUTENUM8);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum8.
     * @param value value to set the AttributeNum8
     */
    public void setAttributeNum8(Number value) {
        setAttributeInternal(ATTRIBUTENUM8, value);
    }

    /**
     * Gets the attribute value for AttributeNum9, using the alias name AttributeNum9.
     * @return the AttributeNum9
     */
    public Number getAttributeNum9() {
        return (Number)getAttributeInternal(ATTRIBUTENUM9);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum9.
     * @param value value to set the AttributeNum9
     */
    public void setAttributeNum9(Number value) {
        setAttributeInternal(ATTRIBUTENUM9, value);
    }

    /**
     * Gets the attribute value for AttributeNum10, using the alias name AttributeNum10.
     * @return the AttributeNum10
     */
    public Number getAttributeNum10() {
        return (Number)getAttributeInternal(ATTRIBUTENUM10);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum10.
     * @param value value to set the AttributeNum10
     */
    public void setAttributeNum10(Number value) {
        setAttributeInternal(ATTRIBUTENUM10, value);
    }

    /**
     * Gets the attribute value for AttributeDate1, using the alias name AttributeDate1.
     * @return the AttributeDate1
     */
    public Date getAttributeDate1() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate1.
     * @param value value to set the AttributeDate1
     */
    public void setAttributeDate1(Date value) {
        setAttributeInternal(ATTRIBUTEDATE1, value);
    }

    /**
     * Gets the attribute value for AttributeDate2, using the alias name AttributeDate2.
     * @return the AttributeDate2
     */
    public Date getAttributeDate2() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate2.
     * @param value value to set the AttributeDate2
     */
    public void setAttributeDate2(Date value) {
        setAttributeInternal(ATTRIBUTEDATE2, value);
    }

    /**
     * Gets the attribute value for AttributeDate3, using the alias name AttributeDate3.
     * @return the AttributeDate3
     */
    public Date getAttributeDate3() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate3.
     * @param value value to set the AttributeDate3
     */
    public void setAttributeDate3(Date value) {
        setAttributeInternal(ATTRIBUTEDATE3, value);
    }

    /**
     * Gets the attribute value for AttributeDate4, using the alias name AttributeDate4.
     * @return the AttributeDate4
     */
    public Date getAttributeDate4() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate4.
     * @param value value to set the AttributeDate4
     */
    public void setAttributeDate4(Date value) {
        setAttributeInternal(ATTRIBUTEDATE4, value);
    }

    /**
     * Gets the attribute value for AttributeDate5, using the alias name AttributeDate5.
     * @return the AttributeDate5
     */
    public Date getAttributeDate5() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate5.
     * @param value value to set the AttributeDate5
     */
    public void setAttributeDate5(Date value) {
        setAttributeInternal(ATTRIBUTEDATE5, value);
    }

    /**
     * Gets the attribute value for IncoTermsValue, using the alias name IncoTermsValue.
     * @return the IncoTermsValue
     */
    public String getIncoTermsValue() {
        return (String)getAttributeInternal(INCOTERMSVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncoTermsValue.
     * @param value value to set the IncoTermsValue
     */
    public void setIncoTermsValue(String value) {
        setAttributeInternal(INCOTERMSVALUE, value);
    }

    /**
     * Gets the attribute value for ShipmentType, using the alias name ShipmentType.
     * @return the ShipmentType
     */
    public String getShipmentType() {
        return (String)getAttributeInternal(SHIPMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentType.
     * @param value value to set the ShipmentType
     */
    public void setShipmentType(String value) {
        setAttributeInternal(SHIPMENTTYPE, value);
    }

    /**
     * Gets the attribute value for ChargableGrossWeight, using the alias name ChargableGrossWeight.
     * @return the ChargableGrossWeight
     */
    public String getChargableGrossWeight() {
        return (String)getAttributeInternal(CHARGABLEGROSSWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChargableGrossWeight.
     * @param value value to set the ChargableGrossWeight
     */
    public void setChargableGrossWeight(String value) {
        setAttributeInternal(CHARGABLEGROSSWEIGHT, value);
    }

    /**
     * Gets the attribute value for TotalCbm, using the alias name TotalCbm.
     * @return the TotalCbm
     */
    public Number getTotalCbm() {
        return (Number)getAttributeInternal(TOTALCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalCbm.
     * @param value value to set the TotalCbm
     */
    public void setTotalCbm(Number value) {
        setAttributeInternal(TOTALCBM, value);
    }

    /**
     * Gets the attribute value for ShortExcessPer, using the alias name ShortExcessPer.
     * @return the ShortExcessPer
     */
    public Number getShortExcessPer() {
        return (Number)getAttributeInternal(SHORTEXCESSPER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShortExcessPer.
     * @param value value to set the ShortExcessPer
     */
    public void setShortExcessPer(Number value) {
        setAttributeInternal(SHORTEXCESSPER, value);
    }

    /**
     * Gets the attribute value for ShortExcessQty, using the alias name ShortExcessQty.
     * @return the ShortExcessQty
     */
    public Number getShortExcessQty() {
        return (Number)getAttributeInternal(SHORTEXCESSQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShortExcessQty.
     * @param value value to set the ShortExcessQty
     */
    public void setShortExcessQty(Number value) {
        setAttributeInternal(SHORTEXCESSQTY, value);
    }

    /**
     * Gets the attribute value for PackListNo, using the alias name PackListNo.
     * @return the PackListNo
     */
    public Number getPackListNo() {
        return (Number)getAttributeInternal(PACKLISTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackListNo.
     * @param value value to set the PackListNo
     */
    public void setPackListNo(Number value) {
        setAttributeInternal(PACKLISTNO, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for TransportationMode, using the alias name TransportationMode.
     * @return the TransportationMode
     */
    public String getTransportationMode() {
        return (String)getAttributeInternal(TRANSPORTATIONMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransportationMode.
     * @param value value to set the TransportationMode
     */
    public void setTransportationMode(String value) {
        setAttributeInternal(TRANSPORTATIONMODE, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for OrderItemId, using the alias name OrderItemId.
     * @return the OrderItemId
     */
    public Number getOrderItemId() {
        return (Number)getAttributeInternal(ORDERITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderItemId.
     * @param value value to set the OrderItemId
     */
    public void setOrderItemId(Number value) {
        setAttributeInternal(ORDERITEMID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ItemName, using the alias name ItemName.
     * @return the ItemName
     */
    public String getItemName() {
        return (String)getAttributeInternal(ITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemName.
     * @param value value to set the ItemName
     */
    public void setItemName(String value) {
        setAttributeInternal(ITEMNAME, value);
    }

    /**
     * Gets the attribute value for FinalUnitPrice, using the alias name FinalUnitPrice.
     * @return the FinalUnitPrice
     */
    public Number getFinalUnitPrice() {
        return (Number)getAttributeInternal(FINALUNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinalUnitPrice.
     * @param value value to set the FinalUnitPrice
     */
    public void setFinalUnitPrice(Number value) {
        setAttributeInternal(FINALUNITPRICE, value);
    }

    /**
     * Gets the attribute value for ChildStyleNo, using the alias name ChildStyleNo.
     * @return the ChildStyleNo
     */
    public String getChildStyleNo() {
        return (String)getAttributeInternal(CHILDSTYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChildStyleNo.
     * @param value value to set the ChildStyleNo
     */
    public void setChildStyleNo(String value) {
        setAttributeInternal(CHILDSTYLENO, value);
    }

    /**
     * Gets the attribute value for HangerCost, using the alias name HangerCost.
     * @return the HangerCost
     */
    public Number getHangerCost() {
        return (Number)getAttributeInternal(HANGERCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for HangerCost.
     * @param value value to set the HangerCost
     */
    public void setHangerCost(Number value) {
        setAttributeInternal(HANGERCOST, value);
    }

    /**
     * Gets the attribute value for HangerStyle, using the alias name HangerStyle.
     * @return the HangerStyle
     */
    public String getHangerStyle() {
        return (String)getAttributeInternal(HANGERSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HangerStyle.
     * @param value value to set the HangerStyle
     */
    public void setHangerStyle(String value) {
        setAttributeInternal(HANGERSTYLE, value);
    }

    /**
     * Gets the attribute value for SizerCost, using the alias name SizerCost.
     * @return the SizerCost
     */
    public Number getSizerCost() {
        return (Number)getAttributeInternal(SIZERCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizerCost.
     * @param value value to set the SizerCost
     */
    public void setSizerCost(Number value) {
        setAttributeInternal(SIZERCOST, value);
    }

    /**
     * Gets the attribute value for SizerStyle, using the alias name SizerStyle.
     * @return the SizerStyle
     */
    public String getSizerStyle() {
        return (String)getAttributeInternal(SIZERSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizerStyle.
     * @param value value to set the SizerStyle
     */
    public void setSizerStyle(String value) {
        setAttributeInternal(SIZERSTYLE, value);
    }

    /**
     * Gets the attribute value for BpoId, using the alias name BpoId.
     * @return the BpoId
     */
    public Number getBpoId() {
        return (Number)getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoId.
     * @param value value to set the BpoId
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity CiHeadersEOImpl.
     */
    public CiHeadersEOImpl getCiHeaders() {
        return (CiHeadersEOImpl)getAttributeInternal(CIHEADERS);
    }

    /**
     * Sets <code>value</code> as the associated entity CiHeadersEOImpl.
     */
    public void setCiHeaders(CiHeadersEOImpl value) {
        setAttributeInternal(CIHEADERS, value);
    }


    /**
     * @param expCiLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number expCiLineId) {
        return new Key(new Object[]{expCiLineId});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("IEDOC_EXP_CI_LINES_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        this.setExpCiLineId(sVal);
        //cust_mnj_ont_pkg.cust_mnj_packassort_srno
        System.out.println("OK");
      //  setShpckassortNo(new oracle.jbo.domain.Number(getSrNoString()));
    }

}
